2018-10-14 13:53:02.274558 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 25, in getLocalIp
    GStat.ip = IPAddr
NameError: global name 'GStat' is not defined
 >> NetworkingClass:getLocalIp Status N2018-10-14 13:53:02.298781 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 366, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
 >> JSonClass.sendPost Status N2018-10-14 13:53:27.424573 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 26, in getLocalIp
    GStat.ip = IPAddr
NameError: global name 'GStat' is not defined
 >> NetworkingClass:getLocalIp Status N2018-10-14 13:53:27.438930 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 366, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
 >> JSonClass.sendPost Status N2018-10-14 13:54:46.896468 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 26, in getLocalIp
    GStat.ip = IPAddr
NameError: global name 'GStat' is not defined
 >> NetworkingClass:getLocalIp Status N2018-10-14 13:54:46.910634 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 366, in prepare_url
    raise MissingSchema(error)
MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
 >> JSonClass.sendPost Status N2018-10-14 13:55:41.087773 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 26, in getLocalIp
    GStat.ip = IPAddr
NameError: global name 'GStat' is not defined
 >> NetworkingClass:getLocalIp Status N2018-10-14 13:55:41.162591 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 80, in sendPost
    self.dbg.say('machine=>>>>>' + ds['machine'],'JSonClass.sendPost')
KeyError: 'machine'
 >> JSonClass.sendPost Status N2018-10-14 13:56:18.951376 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 26, in getLocalIp
    GStat.ip = IPAddr
NameError: global name 'GStat' is not defined
 >> NetworkingClass:getLocalIp Status N2018-10-17 03:19:30.570607 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-17 03:52:03.466900 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 36, in getLocalIp
    return IPAddr
NameError: global name 'IPAddr' is not defined
 >> NetworkingClass:getLocalIp Status N2018-10-17 03:53:44.910193 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 36, in getLocalIp
    return IPAddr
NameError: global name 'IPAddr' is not defined
 >> NetworkingClass:getLocalIp Status N2018-10-17 04:03:36.703143 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 36, in getLocalIp
    return IPAddr
NameError: global name 'IPAddr' is not defined
 >> NetworkingClass:getLocalIp Status N2018-10-17 04:03:36.765156 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 80, in sendPost
    self.dbg.say('machine=>>>>>' + ds['result'],'JSonClass.sendPost')
TypeError: string indices must be integers
 >> JSonClass.sendPost Status N2018-10-17 04:04:07.889142 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 36, in getLocalIp
    return IPAddr
NameError: global name 'IPAddr' is not defined
 >> NetworkingClass:getLocalIp Status N2018-10-17 04:04:07.957813 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 80, in sendPost
    self.dbg.say('machine=>>>>>' + str( ds['result']) ,'JSonClass.sendPost')
TypeError: string indices must be integers
 >> JSonClass.sendPost Status N2018-10-17 04:04:15.984881 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 36, in getLocalIp
    return IPAddr
NameError: global name 'IPAddr' is not defined
 >> NetworkingClass:getLocalIp Status N2018-10-17 04:04:16.058733 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 80, in sendPost
    self.dbg.say('machine=>>>>>' + str( ds['result']) ,'JSonClass.sendPost')
TypeError: string indices must be integers
 >> JSonClass.sendPost Status N2018-10-17 04:04:45.986081 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 80, in sendPost
    self.dbg.say('machine=>>>>>' + str( ds['result']) ,'JSonClass.sendPost')
TypeError: string indices must be integers
 >> JSonClass.sendPost Status N2018-10-18 13:48:33.452108 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 77, in sendPost
    ds=r.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-18 13:53:04.848005 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 470, in begin
    self.msg = HTTPMessage(self.fp, 0)
  File "/usr/lib/python2.7/mimetools.py", line 25, in __init__
    rfc822.Message.__init__(self, fp, seekable)
  File "/usr/lib/python2.7/rfc822.py", line 108, in __init__
    self.readheaders()
  File "/usr/lib/python2.7/httplib.py", line 334, in readheaders
    elif self.iscomment(line):
  File "/usr/lib/python2.7/rfc822.py", line 224, in iscomment
    def iscomment(self, line):
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:53:05.463908 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:53:05.706064 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 470, in begin
    self.msg = HTTPMessage(self.fp, 0)
  File "/usr/lib/python2.7/mimetools.py", line 25, in __init__
    rfc822.Message.__init__(self, fp, seekable)
  File "/usr/lib/python2.7/rfc822.py", line 108, in __init__
    self.readheaders()
  File "/usr/lib/python2.7/httplib.py", line 344, in readheaders
    self.addheader(headerseen, line[len(headerseen)+1:].strip())
  File "/usr/lib/python2.7/httplib.py", line 259, in addheader
    prev = self.dict.get(key)
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:53:05.900104 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 378, in prepare_url
    host = idna.encode(host, uts46=True).decode('utf-8')
  File "/usr/lib/python2.7/dist-packages/requests/packages/idna/core.py", line 340, in encode
    s = uts46_remap(s, std3_rules, transitional)
  File "/usr/lib/python2.7/dist-packages/requests/packages/idna/core.py", line 312, in uts46_remap
    for pos, char in enumerate(domain):
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:53:06.080130 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 32, in getLocalIp
    eth0Ip=check_output(['hostname', '-I']) #works
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1000, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "/usr/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
 >> NetworkingClass:getLocalIp Status N2018-10-18 13:53:06.231768 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 503, in send
    return self.build_response(request, resp)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 250, in build_response
    response = Response()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 587, in __init__
    self.headers = CaseInsensitiveDict()
  File "/usr/lib/python2.7/dist-packages/requests/structures.py", line 46, in __init__
    self.update(data, **kwargs)
  File "/usr/lib/python2.7/_abcoll.py", line 559, in update
    if len(args) > 1:
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:54:26.094476 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='192.168.0.xn--100-', port=80): Max retries exceeded with url: /webroot/smartplay.com/autowifi/read.php?serial=b8:27:eb:7b:95:b6%0A (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x75ec4950>: Failed to establish a new connection: [Errno -2] Name or service not known',))
 >> JSonClass.sendPost Status N2018-10-18 13:54:26.297335 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 851, in send
    if hasattr(data,'read') and not isinstance(data, array):
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:54:26.518941 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 32, in getLocalIp
    eth0Ip=check_output(['hostname', '-I']) #works
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1000, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "/usr/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
 >> NetworkingClass:getLocalIp Status N2018-10-18 13:54:26.525624 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 32, in getLocalIp
    eth0Ip=check_output(['hostname', '-I']) #works
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1010, in _execute_child
    _close_in_parent(c2pwrite)
  File "/usr/lib/python2.7/subprocess.py", line 902, in _close_in_parent
    os.close(fd)
OSError: [Errno 9] Bad file descriptor
 >> NetworkingClass:getLocalIp Status N2018-10-18 13:54:26.700183 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 32, in getLocalIp
    eth0Ip=check_output(['hostname', '-I']) #works
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1000, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "/usr/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
 >> NetworkingClass:getLocalIp Status N2018-10-18 13:54:26.700399 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 32, in getLocalIp
    eth0Ip=check_output(['hostname', '-I']) #works
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1000, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "/usr/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
 >> NetworkingClass:getLocalIp Status N2018-10-18 13:54:26.704080 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 32, in getLocalIp
    eth0Ip=check_output(['hostname', '-I']) #works
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1010, in _execute_child
    _close_in_parent(c2pwrite)
  File "/usr/lib/python2.7/subprocess.py", line 902, in _close_in_parent
    os.close(fd)
OSError: [Errno 9] Bad file descriptor
 >> NetworkingClass:getLocalIp Status N2018-10-18 13:54:26.885049 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 32, in getLocalIp
    eth0Ip=check_output(['hostname', '-I']) #works
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1000, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "/usr/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
 >> NetworkingClass:getLocalIp Status N2018-10-18 13:54:26.889347 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 489, in readline
    nl = data.find('\n', 0, left)
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:54:26.892353 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 32, in getLocalIp
    eth0Ip=check_output(['hostname', '-I']) #works
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 916, in _execute_child
    self.pid = os.fork()
KeyboardInterrupt
 >> NetworkingClass:getLocalIp Status N2018-10-18 13:54:27.062692 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:54:27.062625 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 302, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 378, in prepare_url
    host = idna.encode(host, uts46=True).decode('utf-8')
  File "/usr/lib/python2.7/dist-packages/requests/packages/idna/core.py", line 355, in encode
    result.append(alabel(label))
  File "/usr/lib/python2.7/dist-packages/requests/packages/idna/core.py", line 261, in alabel
    label = label.encode('ascii')
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:54:27.062746 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:55:11.082759 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 32, in getLocalIp
    eth0Ip=check_output(['hostname', '-I']) #works
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 916, in _execute_child
    self.pid = os.fork()
KeyboardInterrupt
 >> NetworkingClass:getLocalIp Status N2018-10-18 13:55:11.432815 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 58, in sendPost
    self.dbg.say('sending post','JSonClass.sendPost')
  File "/home/pi/jp/SmartPlay/pythons/Dbg.py", line 40, in say
    print str(    str(msg) + "  Function=  " + str(clsMethod)  )
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:55:11.649440 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 32, in getLocalIp
    eth0Ip=check_output(['hostname', '-I']) #works
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1000, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "/usr/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
 >> NetworkingClass:getLocalIp Status N2018-10-18 13:55:12.113396 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 409, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/util/timeout.py", line 97, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:55:12.330280 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 32, in getLocalIp
    eth0Ip=check_output(['hostname', '-I']) #works
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1000, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "/usr/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
 >> NetworkingClass:getLocalIp Status N2018-10-18 13:56:28.367744 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 32, in getLocalIp
    eth0Ip=check_output(['hostname', '-I']) #works
  File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1000, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "/usr/lib/python2.7/subprocess.py", line 121, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
 >> NetworkingClass:getLocalIp Status N2018-10-18 13:56:28.631684 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1118, in getresponse
    response = self.response_class(*args, **kwds)
  File "/usr/lib/python2.7/httplib.py", line 383, in __init__
    self.version = _UNKNOWN # HTTP-Version
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:56:28.835216 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='192.168.0.xn--100-', port=80): Max retries exceeded with url: /webroot/smartplay.com/autowifi/read.php?serial=b8:27:eb:7b:95:b6%0A (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x75e7a710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
 >> JSonClass.sendPost Status N2018-10-18 13:56:28.991765 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 13:56:29.155910 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 582, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 255, in _get_conn
    return conn or self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 212, in _new_conn
    self.num_connections, self.host)
  File "/usr/lib/python2.7/logging/__init__.py", line 1155, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1295, in handle
    if (not self.disabled) and self.filter(record):
  File "/usr/lib/python2.7/logging/__init__.py", line 616, in filter
    for f in self.filters:
KeyboardInterrupt
 >> JSonClass.sendPost Status N2018-10-18 14:32:49.379315 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
 >> JSonClass.sendPost Status N2018-10-18 14:32:49.379312 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
 >> JSonClass.sendPost Status N2018-10-18 15:42:04.315516 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 33, in getLocalIp
    print "Wlan0=" + eth0Ip.split()[1]
IndexError: list index out of range
 >> NetworkingClass:getLocalIp Status N2018-10-18 15:42:25.646449 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 33, in getLocalIp
    print "Wlan0=" + eth0Ip.split()[1]
IndexError: list index out of range
 >> NetworkingClass:getLocalIp Status N2018-10-18 15:46:09.091647 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 44, in getWlanIp
    print "Wlan0=" + eth0Ip.split()[1]
IndexError: list index out of range
 >> NetworkingClass:getLocalIp Status N2018-10-18 15:46:12.192973 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 44, in getWlanIp
    print "Wlan0=" + eth0Ip.split()[1]
IndexError: list index out of range
 >> NetworkingClass:getLocalIp Status N2018-10-18 15:47:37.122043 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 46, in getWlanIp
    ips=eth0Ip.split()[1]
IndexError: list index out of range
 >> NetworkingClass:getLocalIp Status N2018-10-18 15:47:40.217594 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 46, in getWlanIp
    ips=eth0Ip.split()[1]
IndexError: list index out of range
 >> NetworkingClass:getLocalIp Status N2018-10-19 04:13:05.125457 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 46, in getWlanIp
    ips=eth0Ip.split()[1]
IndexError: list index out of range
 >> NetworkingClass:getLocalIp Status N2018-10-19 04:13:08.229684 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/NetworkingClass.py", line 46, in getWlanIp
    ips=eth0Ip.split()[1]
IndexError: list index out of range
 >> NetworkingClass:getLocalIp Status N2018-10-19 04:23:22.181662 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 75, in sendPost
    self.dbg.say(str(r.json()),'JSonClass.sendPost')
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-19 04:23:25.225576 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 75, in sendPost
    self.dbg.say(str(r.json()),'JSonClass.sendPost')
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-19 04:24:05.313856 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 75, in sendPost
    self.dbg.say(str(r.json()),'JSonClass.sendPost')
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-19 04:26:46.377743 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 75, in sendPost
    self.dbg.say(str(r.json()),'JSonClass.sendPost')
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-19 04:26:49.433543 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 75, in sendPost
    self.dbg.say(str(r.json()),'JSonClass.sendPost')
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-19 04:28:29.887626 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 75, in sendPost
    self.dbg.say(str(r.json()),'JSonClass.sendPost')
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-19 04:29:17.204784 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 75, in sendPost
    self.dbg.say(str(r.json()),'JSonClass.sendPost')
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-19 04:30:08.949251 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 75, in sendPost
    self.dbg.say(str(r.json()),'JSonClass.sendPost')
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-19 04:31:53.656002 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 75, in sendPost
    self.dbg.say(str(r.json()),'JSonClass.sendPost')
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-19 04:31:56.702811 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 75, in sendPost
    self.dbg.say(str(r.json()),'JSonClass.sendPost')
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-19 04:34:45.184977 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 75, in sendPost
    self.dbg.say(str(r.json()),'JSonClass.sendPost')
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-19 04:34:48.233331 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 75, in sendPost
    self.dbg.say(str(r.json()),'JSonClass.sendPost')
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 >> JSonClass.sendPost Status N2018-10-25 16:57:25.415511 Traceback (most recent call last):
  File "/home/pi/jp/SmartPlay/pythons/JSonClass.py", line 64, in sendPost
    r = requests.post(url, data=dataInput, headers=headers)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 582, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 255, in _get_conn
    return conn or self._new_conn()
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 212, in _new_conn
    self.num_connections, self.host)
  File "/usr/lib/python2.7/logging/__init__.py", line 1155, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 957, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 885, in emit
    self.flush()
  File "/usr/lib/python2.7/logging/__init__.py", line 845, in flush
    self.stream.flush()
KeyboardInterrupt
 >> JSonClass.sendPost Status N